Bootstrap: docker
Registry: localhost:5000
Namespace:
From: fenics2019-omega-h

%files
    WELCOME.Singularity /usr/local/share/WELCOME

%post
    chmod a+r /usr/local/share/WELCOME
    ldconfig

%runscript
    cat /usr/local/share/WELCOME 
    exec /bin/bash -i
